# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacation_request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employees', models.ManyToManyField(related_name='employee_departments', to=settings.AUTH_USER_MODEL)),
                ('managers', models.ManyToManyField(related_name='manager_departments', to=settings.AUTH_USER_MODEL)),
                ('modificators', models.ManyToManyField(blank=True, to='vacation_request.Modificator')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('modificators', models.ManyToManyField(blank=True, to='vacation_request.Modificator')),
            ],
        ),
    ]
