# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(related_name='employee_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='managers',
            field=models.ManyToManyField(related_name='manager_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
