# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_request', '0001_initial'),
        ('company', '0002_auto_20170207_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='modificators',
            field=models.ManyToManyField(blank=True, to='vacation_request.Modificator'),
        ),
        migrations.AddField(
            model_name='job',
            name='modificators',
            field=models.ManyToManyField(blank=True, to='vacation_request.Modificator'),
        ),
    ]
