# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_auto_20170210_2215'),
        ('vacation_request', '0001_initial'),
        ('auth_account', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='request_types',
            field=models.ManyToManyField(related_name='user_groups', to='vacation_request.RequestType'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(to='auth_account.Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Job'),
        ),
        migrations.AddField(
            model_name='user',
            name='modificators',
            field=models.ManyToManyField(blank=True, to='vacation_request.Modificator'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
