# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0002_auto_20170207_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
