# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='period',
            field=models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=100),
            preserve_default=False,
        ),
    ]
