# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 00:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacation_request', '0002_auto_20170216_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='approvals',
        ),
        migrations.AddField(
            model_name='request',
            name='approvals',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
