# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacation_request', '0003_auto_20170219_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AddField(
            model_name='request',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
