# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20170216_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='datetime',
            new_name='creation_date',
        ),
    ]
